sys:
  batch: 10000
  partition: 10
  maxPollWait: 5000
  cleanInterval: 60000
  syncTriggerInterval: 60000
  dataKeepHours: 24
  workDirectory: "d:/temp"


db:
  - name: pgdata
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://app-dev-01:21769/pgdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
    createIndex: true
  - name: srv
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://app-dev-01:21769/srv_directory
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
    createIndex: true

sync:
  - sourceDb: pgdata
    targetDb: srv
    sourceSchema: dbsync
    sourceTable: test01
    sourceKeys: vin,brand_id