sys:
  batch: 10000
  partition: 10
  maxPollWait: 5000
  cleanInterval: 3600000
  dataKeepHours: 24


db:
  - name: ppt
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.210:21769/pgdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
  - name: masterdata
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.210:21769/masterdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
  - name: sit
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.211:21769/pgdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
  - name: prd
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.213:21769/pgdata
    user: replica_user
    password: Mingjueinfo2015_replica
    sysSchema: dbsync
  - name: staging
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://172.31.2.171:21768/pgdata
    user: pgadmin
    password: Mingjueinfo2015_db
    sysSchema: dbsync

sync:
  - sourceDb: masterdata
    targetDb: sit,ppt,prd,staging
    sourceSchema: public
    sourceTable: mj_vin_brandid_solidify
    sourceKeys: vin
  - sourceDb: staging
    targetDb: prd
    sourceSchema: frs
    sourceTable: parts_mjsid
    sourceKeys: 'mjsid,part_name,image,image_index,part_number,action_type'
    insertCondition: NEW.is_commit=1
    updateCondition: NEW.is_commit=1
    deleteCondition: OLD.is_commit=1
  - sourceDb: staging
    targetDb: prd
    sourceSchema: frs
    sourceTable: parts_result
    sourceKeys: 'vin,part_name,image,image_index,part_number,action_type'
    insertCondition: NEW.is_commit=1
    updateCondition: NEW.is_commit=1
    deleteCondition: OLD.is_commit=1
  - sourceDb: staging
    targetDb: prd
    sourceSchema: frs
    sourceTable: vin_mjsid
    sourceKeys: vin
    insertCondition: NEW.is_commit=1
    updateCondition: NEW.is_commit=1
    deleteCondition: OLD.is_commit=1
  - sourceDb: staging
    targetDb: prd
    sourceSchema: frs
    sourceTable: vin_parse
    sourceKeys: vin
    insertCondition: NEW.is_commit=1
    updateCondition: NEW.is_commit=1
    deleteCondition: OLD.is_commit=1