sys:
  batch: 10000
  partition: 20
  maxPollWait: 5000
  cleanInterval: 60000
  syncTriggerInterval: 60000
  retryInterval: 60000
  dataKeepHours: 24
  workDirectory: "d:/temp"


db:
  - name: pgdata
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://app-dev-01:21769/pgdata
    user: xxx
    password: xxx
    sysSchema: dbsync
    createIndex: true
  - name: srv
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://app-dev-01:21769/srv_directory
    user: xxx
    password: xxx
    sysSchema: dbsync
    createIndex: true

sync:
  - sourceDb: pgdata
    targetDb: srv
    sourceSchema: dbsync
    sourceTable: test01
    sourceKeys: source,part_name,sub_chain
    insertCondition: NEW.is_commit=1
    updateCondition: NEW.is_commit=1
    deleteCondition: OLD.is_commit=1