sys:
  batch: 10000
  partition: 20
  maxPollWait: 5000
  cleanInterval: 3600000
  dataKeepHours: 24
  syncTriggerInterval: 300000
  retryInterval: 20000
  endpointPort: 8081
  restartWhenRedStatus: true
  restartWhenBlockedOver: 100
  restartWhenErrorOver: 100


db:
  - name: db1
    type: greenplum
    driver: org.postgresql.Driver
    url: jdbc:postgresql://172.30.1.92:21769/pgdata
    user: gpadmin
    password: Mingjueinfo2015_db
    sysSchema: dbsync
    createIndex: true
    maxPoolSize: 5
  - name: db2
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jump.louyj.com:55501/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: root
    password: mysql!23$
    sysSchema: dbsync
    createIndex: false

sync:
  - sourceDb: db2
    targetDb: db1
    sourceSchema: test
    sourceTable: test01
    sourceKeys: f1,f2
    targetSchema: public