sys:
  batch: 10000
  partition: 10


db:
  - name: staging
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://172.31.2.171:21768/pgdata
    user: pgadmin
    password: Mingjueinfo2015_db
    sysSchema: dbsync

sync:
  - sourceDb: staging
    targetDb: staging
    sourceSchema: dbsync
    sourceTable: test001
    sourceKeys: f1
    targetSchema: dbsync
    targetTable: test002
    insertCondition: null
    updateCondition: null
    deleteCondition: null