sys:
  batch: 10000
  partition: 10
  maxPollWait: 5000
  cleanInterval: 3600000


db:
  - name: ppt
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.210:21769/pgdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
  - name: masterdata
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.210:21769/masterdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync
  - name: sit
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.211:21769/pgdata
    user: pgdata
    password: Mingjueinfo2015_db
    sysSchema: dbsync


sync:
  - sourceDb: masterdata
    targetDb: sit,ppt
    sourceSchema: public
    sourceTable: mj_vin_brandid_solidify
    sourceKeys: vin